### ISSUE TITLE
Output from `transferMarkers`

### ISSUE THREAD

**Issue by thoree** [magnusdv/forrel#11]
`transferMarkers` should perhaps return an error below rather than returning
the last simulation?!:
``` r
library(forrel,quietly = TRUE)
v1 = singleton("V1")
m1 = marker(v1, alleles = 1:100, name = "L1")
v1 = setMarkers(v1, m1)
sim = profileSim(v1, N=2, cond = "L1", seed = 123)
transferMarkers(sim, v1, id = "V1")
#>  id fid mid sex    L1
#>  V1   *   *   1 42/90
```

<sup>Created on 2018-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
Moving this to `pedtools`
