### ISSUE TITLE
Table file input wizard

### ISSUE THREAD

**Issue by knifecake** [magnusdv/forrel#20]
Consider creating a file wizard that lets the user choose what input format they want to provide.

- [x] Choose between tabs, commas or other characters as separators.
- [x] Integrate the module with table file inputs.
- [x] ~~Allow multiple file input and concatenation.~~ Postponed until what other loading formats is clearly defined.
- [x] ~~Choose which columns and/or rows do what in a file.~~ Allow users to transpose the table.
- [x] Predefine defaults for some of the most common input formats (e.g. for the relMix format for allele frecuencies)?
- [ ] Possible heuristic for automatically choosing fields separators: *the field separator is likely the most occurring whitespace character.*

**Comment by magnusdv** [comment]
Is this for pedigree files or frequency databases?

**Comment by knifecake** [comment]
@magnusdv this is for frequency databases and perhaps reference profiles. I assumed not a lot of people would edit pedigree files by hand although extending it to support pedigree files is trivial.

**Comment by knifecake** [comment]
Closing this issue as the module has matured (see c9906f7e9b62b11554c5b9ccf9609afe00a3d739) a bit and is now pretty usable. The idea is that this module can be used whenever the user needs to load tabular data from a delimited file with a format that is not clearly specified (for instance, different users might use different delimiters for their frequency database files, or may have them transposed with respect to others). The module allows the user to customise the parameters that R's `read.table` uses for reading tabular files.

A future implementation of loading from Familias or using pedigree attached genotypes will most likely not use this module.

See inst/exclusionPowerUI/advancedTableFileLoader.R (now [inside the shiny-ui branch](https://github.com/magnusdv/forrel/blob/shiny-gui/inst/exclusionPowerUI/advancedTableFileLoader.R)) for more details.


---

As a side note, the module's documentation does not become available inside the `forrel` package's `man` directory. This is probably a good thing, but if this module proves usable it might be worth to extract it as a shiny gadget.
