### ISSUE TITLE
`exclusionPower` and `founderInbreeding`

### ISSUE THREAD

**Issue by thoree** [magnusdv/forrel#37]
It  appears that founder inbreeding must be specified for the `true` alternative in
`exclusionPower` as the below example shows. Perhaps a clarification is in place
in the documentation
``` r
library(forrel)
#> Loading required package: pedtools
claim = nuclearPed(nch = 1, sex = 2)
true = list(singleton(id = 1), singleton(id = 3, sex = 2))
m1 = marker(claim)
claim = setMarkers(claim, m1)
f = 1/16
founderInbreeding(claim, "1") = f
# founderInbreeding(true[[1]], "1") = f # gives correct result.
exclusionPower(claim, true, ids = c(1,3), plot = F, verbose = F)
#> Total EP: 0.125 
#> Markers inconsistent with pedigree: 0  
#> Markers with potential mismatch: 1 (1) 
#> Expected number of mismatches: 0.125
# exclusionPower gives the same result, ep = 0.125, for f < 1
# and ep = 0.625 for f = 1. I get
p = 0.5
(f*p+(1-f)*p^2)*(1-p)^2 + (f*(1-p)+(1-f)*(1-p)^2)*p^2
#> [1] 0.1328125
```

<sup>Created on 2020-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by magnusdv** [comment]
This behaviour is by design, since `exclusionPower()` offers complete freedom in the specification of `true` and `claim`. 

Both alternatives may have inbred founders (with the same or different coefficients), but this must be set individually for each.

I'd be happy to clarify this in the docs, of course. Do you have a formulation suggestion?

**Comment by thoree** [comment]
The sentence (in Details)
" Both alternatives may have inbred founders (with the same or different
coefficients), but this must be set individually for each."
would clarify this for me.

Thore

man. 15. jun. 2020 kl. 11:16 skrev Magnus Dehli Vigeland <
notifications@github.com>:
