### ISSUE TITLE
kinshipLR problem

### ISSUE THREAD

**Issue by thoree** [magnusdv/forrel#38]
I have a problem with `kinshipLR`. Here's the first example of the documentation:

``` r
library(forrel)
#> Loading required package: pedtools
ids = c("A", "B")
sibs = nuclearPed(children = ids)
sibs = simpleSim(sibs, N = 5, alleles = 1:4, ids = ids, 
                 seed = 123, verbose = FALSE)
halfsibs = relabel(halfSibPed(), old = 4:5, new = ids)
unrel = list(singleton("A"), singleton("B"))
kinshipLR(sibs, halfsibs, unrel)
#> Error in vapply(markers, function(i) likelihood(xx, marker1 = i), FUN.VALUE = 1): values must be length 1,
#>  but FUN(X[[1]]) result is length 5
```

<sup>Created on 2020-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by magnusdv** [comment]
Thanks!

Recent breaking changes in `pedprobr` are causing a some hickups in other packages. This one should be fixed now, can you try again with the latest devel versions of `pedprobr` and `forrel`?

**Comment by thoree** [comment]
Thanks - fine now.

man. 6. jul. 2020 kl. 21:10 skrev Magnus Dehli Vigeland <
notifications@github.com>:
