### ISSUE TITLE
IBDtriangle

### ISSUE THREAD

**Issue by thoree** [magnusdv/forrel#5]
Change IBDtriangle to allow for k0 and k2 on the axes rather than the current greek kappas, eg by changing the argument to allow: kappas = c("k0", "k2)?

**Comment by magnusdv** [comment]
Nice suggestion. This is implemented in

The `kappas` parameter is replaced with explicit `xlab` and `ylab`, and the font size is controled with `cex_lab`.

To get italic labels, use `expression`, e.g.
```r
IBDtriangle(xlab = expression(italic(k[0])), ylab = expression(italic(k[2])))
```
